/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyReadDto"][];
                        "application/json": components["schemas"]["ApiKeyReadDto"][];
                        "text/json": components["schemas"]["ApiKeyReadDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["ApiKeyWriteDto"];
                    "application/json": components["schemas"]["ApiKeyWriteDto"];
                    "text/json": components["schemas"]["ApiKeyWriteDto"];
                    "application/*+json": components["schemas"]["ApiKeyWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyCreatedDto"];
                        "application/json": components["schemas"]["ApiKeyCreatedDto"];
                        "text/json": components["schemas"]["ApiKeyCreatedDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/circle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CircleReadDtoCursorPage"];
                        "application/json": components["schemas"]["CircleReadDtoCursorPage"];
                        "text/json": components["schemas"]["CircleReadDtoCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/circle/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CircleReadDto"];
                        "application/json": components["schemas"]["CircleReadDto"];
                        "text/json": components["schemas"]["CircleReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/circle/by-name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CircleReadDto"];
                        "application/json": components["schemas"]["CircleReadDto"];
                        "text/json": components["schemas"]["CircleReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/circle/{id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReleaseListItemDtoCursorPage"];
                        "application/json": components["schemas"]["ReleaseListItemDtoCursorPage"];
                        "text/json": components["schemas"]["ReleaseListItemDtoCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/circle/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    flavor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarCirclesResponseDto"];
                        "application/json": components["schemas"]["SimilarCirclesResponseDto"];
                        "text/json": components["schemas"]["SimilarCirclesResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlayEventReadDtoCursorPage"];
                        "application/json": components["schemas"]["PlayEventReadDtoCursorPage"];
                        "text/json": components["schemas"]["PlayEventReadDtoCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlayEventWriteDto"];
                    "application/json": components["schemas"]["PlayEventWriteDto"];
                    "text/json": components["schemas"]["PlayEventWriteDto"];
                    "application/*+json": components["schemas"]["PlayEventWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/circle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["CircleUpsertDto"][];
                    "application/json": components["schemas"]["CircleUpsertDto"][];
                    "text/json": components["schemas"]["CircleUpsertDto"][];
                    "application/*+json": components["schemas"]["CircleUpsertDto"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/track/{trackId}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["LyricsWriteDto"];
                    "application/json": components["schemas"]["LyricsWriteDto"];
                    "text/json": components["schemas"]["LyricsWriteDto"];
                    "application/*+json": components["schemas"]["LyricsWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LyricsReadDto"];
                        "application/json": components["schemas"]["LyricsReadDto"];
                        "text/json": components["schemas"]["LyricsReadDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/track/{trackId}/originals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["TrackOriginalsWriteDto"];
                    "application/json": components["schemas"]["TrackOriginalsWriteDto"];
                    "text/json": components["schemas"]["TrackOriginalsWriteDto"];
                    "application/*+json": components["schemas"]["TrackOriginalsWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/search/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/track/{trackId}/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["TrackCreditsWriteDto"];
                    "application/json": components["schemas"]["TrackCreditsWriteDto"];
                    "text/json": components["schemas"]["TrackCreditsWriteDto"];
                    "application/*+json": components["schemas"]["TrackCreditsWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/release/{releaseId}/source-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    releaseId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["ReleaseSourceMetaWriteDto"];
                    "application/json": components["schemas"]["ReleaseSourceMetaWriteDto"];
                    "text/json": components["schemas"]["ReleaseSourceMetaWriteDto"];
                    "application/*+json": components["schemas"]["ReleaseSourceMetaWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/track/{trackId}/hls/playlist.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/track/{trackId}/hls/{bitrate}/playlist.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                    bitrate: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/track/{trackId}/hls/{bitrate}/stream.m4s": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                    bitrate: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/track/{trackId}/dash/manifest.mpd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/track/{trackId}/dash/{bitrate}k/stream.m4s": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: string;
                    bitrate: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OriginalWorkReadDto"][];
                        "application/json": components["schemas"]["OriginalWorkReadDto"][];
                        "text/json": components["schemas"]["OriginalWorkReadDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["OriginalWorkWriteDto"];
                    "application/json": components["schemas"]["OriginalWorkWriteDto"];
                    "text/json": components["schemas"]["OriginalWorkWriteDto"];
                    "application/*+json": components["schemas"]["OriginalWorkWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OriginalWorkReadDto"];
                        "application/json": components["schemas"]["OriginalWorkReadDto"];
                        "text/json": components["schemas"]["OriginalWorkReadDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/work/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OriginalWorkReadDto"];
                        "application/json": components["schemas"]["OriginalWorkReadDto"];
                        "text/json": components["schemas"]["OriginalWorkReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/song/{id}/arrangements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackWithContextCursorPage"];
                        "application/json": components["schemas"]["TrackWithContextCursorPage"];
                        "text/json": components["schemas"]["TrackWithContextCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/work/{workId}/song": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["OriginalSongWriteDto"];
                    "application/json": components["schemas"]["OriginalSongWriteDto"];
                    "text/json": components["schemas"]["OriginalSongWriteDto"];
                    "application/*+json": components["schemas"]["OriginalSongWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OriginalSongReadDto"];
                        "application/json": components["schemas"]["OriginalSongReadDto"];
                        "text/json": components["schemas"]["OriginalSongReadDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistReadDto"][];
                        "application/json": components["schemas"]["PlaylistReadDto"][];
                        "text/json": components["schemas"]["PlaylistReadDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistReadDto"];
                        "application/json": components["schemas"]["PlaylistReadDto"];
                        "text/json": components["schemas"]["PlaylistReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistReadDto"];
                        "application/json": components["schemas"]["PlaylistReadDto"];
                        "text/json": components["schemas"]["PlaylistReadDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlaylistWriteDto"];
                    "application/json": components["schemas"]["PlaylistWriteDto"];
                    "text/json": components["schemas"]["PlaylistWriteDto"];
                    "application/*+json": components["schemas"]["PlaylistWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistReadDto"];
                        "application/json": components["schemas"]["PlaylistReadDto"];
                        "text/json": components["schemas"]["PlaylistReadDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlaylistWriteDto"];
                    "application/json": components["schemas"]["PlaylistWriteDto"];
                    "text/json": components["schemas"]["PlaylistWriteDto"];
                    "application/*+json": components["schemas"]["PlaylistWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistReadDto"];
                        "application/json": components["schemas"]["PlaylistReadDto"];
                        "text/json": components["schemas"]["PlaylistReadDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlistId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    start?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    playlistId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlaylistItemDto"][];
                        "application/json": components["schemas"]["PlaylistItemDto"][];
                        "text/json": components["schemas"]["PlaylistItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlistId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlaylistItemsWriteDto"];
                    "application/json": components["schemas"]["PlaylistItemsWriteDto"];
                    "text/json": components["schemas"]["PlaylistItemsWriteDto"];
                    "application/*+json": components["schemas"]["PlaylistItemsWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlistId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlaylistItemsWriteDto"];
                    "application/json": components["schemas"]["PlaylistItemsWriteDto"];
                    "text/json": components["schemas"]["PlaylistItemsWriteDto"];
                    "application/*+json": components["schemas"]["PlaylistItemsWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlistId}/items/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlistId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["PlaylistItemMoveDto"];
                    "application/json": components["schemas"]["PlaylistItemMoveDto"];
                    "text/json": components["schemas"]["PlaylistItemMoveDto"];
                    "application/*+json": components["schemas"]["PlaylistItemMoveDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QueueItemDto"][];
                        "application/json": components["schemas"]["QueueItemDto"][];
                        "text/json": components["schemas"]["QueueItemDto"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["QueueWriteDto"];
                    "application/json": components["schemas"]["QueueWriteDto"];
                    "text/json": components["schemas"]["QueueWriteDto"];
                    "application/*+json": components["schemas"]["QueueWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["QueueEnqueueDto"];
                    "application/json": components["schemas"]["QueueEnqueueDto"];
                    "text/json": components["schemas"]["QueueEnqueueDto"];
                    "application/*+json": components["schemas"]["QueueEnqueueDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sort?: components["schemas"]["ReleaseSort"];
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReleaseListItemDtoCursorPage"];
                        "application/json": components["schemas"]["ReleaseListItemDtoCursorPage"];
                        "text/json": components["schemas"]["ReleaseListItemDtoCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/release/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReleaseReadDto"];
                        "application/json": components["schemas"]["ReleaseReadDto"];
                        "text/json": components["schemas"]["ReleaseReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/release/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    flavor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarReleasesResponseDto"];
                        "application/json": components["schemas"]["SimilarReleasesResponseDto"];
                        "text/json": components["schemas"]["SimilarReleasesResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/release/{id}/other-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    minScore?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarReleasesResponseDto"];
                        "application/json": components["schemas"]["SimilarReleasesResponseDto"];
                        "text/json": components["schemas"]["SimilarReleasesResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                    offset?: number;
                    locales?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchResponseDto"];
                        "application/json": components["schemas"]["SearchResponseDto"];
                        "text/json": components["schemas"]["SearchResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackReadDto"];
                        "application/json": components["schemas"]["TrackReadDto"];
                        "text/json": components["schemas"]["TrackReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/{id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LyricsReadDto"];
                        "application/json": components["schemas"]["LyricsReadDto"];
                        "text/json": components["schemas"]["LyricsReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    circle_id?: string[];
                    original_work_id?: string[];
                    original_song_id?: string[];
                    release_date_from?: string;
                    release_date_to?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackWithContextCursorPage"];
                        "application/json": components["schemas"]["TrackWithContextCursorPage"];
                        "text/json": components["schemas"]["TrackWithContextCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    count?: number;
                    seed?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackWithContext"][];
                        "application/json": components["schemas"]["TrackWithContext"][];
                        "text/json": components["schemas"]["TrackWithContext"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/by-credit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    name?: string;
                    role?: components["schemas"]["CreditRole"];
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackWithContextCursorPage"];
                        "application/json": components["schemas"]["TrackWithContextCursorPage"];
                        "text/json": components["schemas"]["TrackWithContextCursorPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    v?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrackMapResponseDto"];
                        "application/json": components["schemas"]["TrackMapResponseDto"];
                        "text/json": components["schemas"]["TrackMapResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/track/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    diversify?: boolean;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimilarTracksResponseDto"];
                        "application/json": components["schemas"]["SimilarTracksResponseDto"];
                        "text/json": components["schemas"]["SimilarTracksResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileReadDto"];
                        "application/json": components["schemas"]["UserProfileReadDto"];
                        "text/json": components["schemas"]["UserProfileReadDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UserProfileWriteDto"];
                    "application/json": components["schemas"]["UserProfileWriteDto"];
                    "text/json": components["schemas"]["UserProfileWriteDto"];
                    "application/*+json": components["schemas"]["UserProfileWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileReadDto"];
                        "application/json": components["schemas"]["UserProfileReadDto"];
                        "text/json": components["schemas"]["UserProfileReadDto"];
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json-patch+json": components["schemas"]["UserProfileWriteDto"];
                    "application/json": components["schemas"]["UserProfileWriteDto"];
                    "text/json": components["schemas"]["UserProfileWriteDto"];
                    "application/*+json": components["schemas"]["UserProfileWriteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileReadDto"];
                        "application/json": components["schemas"]["UserProfileReadDto"];
                        "text/json": components["schemas"]["UserProfileReadDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfileReadDto"];
                        "application/json": components["schemas"]["UserProfileReadDto"];
                        "text/json": components["schemas"]["UserProfileReadDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiKeyCreatedDto: {
            key?: string | null;
            /** @example key_00000000000000000000000000 */
            id?: string;
            name?: string | null;
            key_prefix?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        ApiKeyReadDto: {
            /** @example key_00000000000000000000000000 */
            id?: string;
            name?: string | null;
            key_prefix?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        ApiKeyWriteDto: {
            name: string;
        };
        ArtworkReadDto: {
            /** @example art_00000000000000000000000000 */
            id?: string;
            colors?: string[] | null;
            variants?: components["schemas"]["ArtworkVariantDto"][] | null;
        };
        ArtworkVariantDto: {
            /** Format: int32 */
            size_px?: number;
            /** @example file_00000000000000000000000000 */
            asset_id?: string;
        };
        CircleReadDto: {
            /** @example cir_00000000000000000000000000 */
            id?: string;
            name?: string | null;
            status?: components["schemas"]["CircleStatus"];
            /** Format: date */
            established?: string | null;
            country?: string | null;
            alias?: string[] | null;
            website?: components["schemas"]["CircleWebsiteDto"][] | null;
        };
        CircleReadDtoCursorPage: {
            items?: components["schemas"]["CircleReadDto"][] | null;
            next?: string | null;
        };
        CircleSlimDto: {
            /** @example cir_00000000000000000000000000 */
            id?: string;
            name?: string | null;
        };
        /** @enum {string} */
        CircleStatus: "active" | "inactive" | "disbanded" | "transfer" | "unknown" | "unset";
        CircleUpsertDto: {
            name: string | null;
            status?: components["schemas"]["CircleStatus"];
            /** Format: date */
            established?: string | null;
            country?: string | null;
            alias?: string[] | null;
            websites?: components["schemas"]["CircleWebsiteUpsertDto"][] | null;
        };
        CircleWebsiteDto: {
            url?: string | null;
            invalid?: boolean;
        };
        CircleWebsiteUpsertDto: {
            url: string | null;
            invalid?: boolean;
        };
        /** @enum {string} */
        CreditRole: "arranger" | "composer" | "vocalist" | "lyricist" | "performer" | "staff";
        DiscReadDto: {
            /** @example dsc_00000000000000000000000000 */
            id?: string;
            /** Format: int32 */
            disc_number?: number;
            name?: string | null;
            tracks?: components["schemas"]["TrackListItemDto"][] | null;
        };
        LocalizedField: {
            default: string;
            en?: string | null;
            zh?: string | null;
            jp?: string | null;
        };
        LyricsLine: {
            /** Format: int32 */
            index: number;
            /** Format: date-span */
            time?: string | null;
            blocks: components["schemas"]["LyricsText"][] | null;
        };
        LyricsReadDto: {
            /** @example lyr_00000000000000000000000000 */
            id?: string;
            variants?: components["schemas"]["LyricsVariant"][] | null;
            reference_url?: string | null;
        };
        LyricsText: {
            lang: string | null;
            text: string | null;
            ruby?: components["schemas"]["Ruby"][] | null;
        };
        LyricsVariant: {
            variant?: string | null;
            lines: components["schemas"]["LyricsLine"][] | null;
        };
        LyricsWriteDto: {
            variants: components["schemas"]["LyricsVariant"][] | null;
            reference_url?: string | null;
        };
        OriginalSongReadDto: {
            /** @example song_00000000000000000000000000 */
            id?: string;
            external_key?: string | null;
            title?: components["schemas"]["LocalizedField"];
            /** Format: int32 */
            track_index?: number | null;
            external_ref?: string | null;
        };
        OriginalSongSlimDto: {
            /** @example song_00000000000000000000000000 */
            id?: string;
            title?: components["schemas"]["LocalizedField"];
        };
        OriginalSongWriteDto: {
            external_key?: string | null;
            title?: components["schemas"]["LocalizedField"];
            /** Format: int32 */
            track_index?: number | null;
            external_ref?: string | null;
        };
        OriginalWorkReadDto: {
            /** @example work_00000000000000000000000000 */
            id?: string;
            external_key?: string | null;
            work_type?: string | null;
            full_name?: components["schemas"]["LocalizedField"];
            short_name?: components["schemas"]["LocalizedField"];
            external_ref?: string | null;
            songs?: components["schemas"]["OriginalSongReadDto"][] | null;
        };
        OriginalWorkWriteDto: {
            external_key?: string | null;
            work_type?: string | null;
            full_name?: components["schemas"]["LocalizedField"];
            short_name?: components["schemas"]["LocalizedField"];
            external_ref?: string | null;
        };
        PlayEventReadDto: {
            /** Format: date-time */
            played_at?: string;
            source?: components["schemas"]["PlaySource"];
            /** Format: int32 */
            ms_played?: number | null;
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
        };
        PlayEventReadDtoCursorPage: {
            items?: components["schemas"]["PlayEventReadDto"][] | null;
            next?: string | null;
        };
        PlayEventWriteDto: {
            /** @example trk_00000000000000000000000000 */
            track_id?: string;
            source?: components["schemas"]["PlaySource"];
            /** Format: int32 */
            ms_played?: number | null;
        };
        /** @enum {string} */
        PlaySource: "playlist" | "album" | "shuffle" | "similar" | "search" | "unknown";
        PlaylistItemDto: {
            /** Format: int32 */
            position?: number;
            /** Format: date-time */
            added_at?: string;
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
        };
        PlaylistItemMoveDto: {
            /** @example trk_00000000000000000000000000 */
            track_id?: string;
            /** Format: int32 */
            to_position?: number;
        };
        PlaylistItemsWriteDto: {
            track_ids: string[] | null;
        };
        /** @enum {string} */
        PlaylistKind: "normal" | "favorite";
        PlaylistReadDto: {
            /** @example pls_00000000000000000000000000 */
            id?: string;
            name?: string | null;
            kind?: components["schemas"]["PlaylistKind"];
            visibility?: components["schemas"]["PlaylistVisibility"];
            /** @example usr_00000000000000000000000000 */
            owner_id?: string;
            owner_display_name?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_modified?: string;
            /** Format: int32 */
            track_count?: number;
        };
        /** @enum {string} */
        PlaylistVisibility: "public" | "private" | "unlisted";
        PlaylistWriteDto: {
            name: string | null;
            visibility?: components["schemas"]["PlaylistVisibility"];
        };
        QueueEnqueueDto: {
            track_ids: string[] | null;
            at_front?: boolean;
        };
        QueueItemDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            position?: number;
            /** Format: date-time */
            enqueued_at?: string;
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
        };
        QueueWriteDto: {
            track_ids: string[] | null;
        };
        ReleaseListItemDto: {
            /** @example rel_00000000000000000000000000 */
            id?: string;
            name?: components["schemas"]["LocalizedField"];
            /** Format: date */
            release_date?: string | null;
            release_convention?: string | null;
            catalog_number?: string | null;
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
            /** Format: int32 */
            track_count?: number;
        };
        ReleaseListItemDtoCursorPage: {
            items?: components["schemas"]["ReleaseListItemDto"][] | null;
            next?: string | null;
        };
        ReleaseReadDto: {
            /** @example rel_00000000000000000000000000 */
            id?: string;
            name?: components["schemas"]["LocalizedField"];
            /** Format: date */
            release_date?: string | null;
            release_convention?: string | null;
            catalog_number?: string | null;
            websites?: string[] | null;
            data_sources?: string[] | null;
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            artwork?: components["schemas"]["ArtworkReadDto"];
            discs?: components["schemas"]["DiscReadDto"][] | null;
        };
        ReleaseSlimDto: {
            /** @example rel_00000000000000000000000000 */
            id?: string;
            name?: components["schemas"]["LocalizedField"];
        };
        /** @enum {string} */
        ReleaseSort: "name" | "date";
        ReleaseSourceMetaWriteDto: {
            catalog_number?: string | null;
            website?: string | null;
            data_source?: string | null;
        };
        Ruby: {
            /** Format: int32 */
            index: number;
            /** Format: int32 */
            length: number;
            text: string | null;
        };
        SearchHitDto: {
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
            highlights?: {
                [key: string]: unknown;
            } | null;
        };
        SearchResponseDto: {
            query?: string | null;
            items?: components["schemas"]["SearchHitDto"][] | null;
            /** Format: int64 */
            estimated_total_hits?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int32 */
            offset?: number;
            /** Format: int64 */
            processing_time_ms?: number;
        };
        SimilarCircleItemDto: {
            circle?: components["schemas"]["CircleSlimDto"];
            /** Format: float */
            score_style?: number;
            /** Format: float */
            score_raw?: number;
            /** Format: float */
            score_kde?: number;
            /** Format: float */
            relevance?: number;
        };
        SimilarCirclesResponseDto: {
            items?: components["schemas"]["SimilarCircleItemDto"][] | null;
            flavor?: string | null;
            model?: string | null;
        };
        SimilarReleaseItemDto: {
            release?: components["schemas"]["ReleaseSlimDto"];
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            /** Format: float */
            score_style?: number;
            /** Format: float */
            score_raw?: number;
            /** Format: float */
            score_kde?: number;
            /** Format: float */
            relevance?: number;
        };
        SimilarReleasesResponseDto: {
            items?: components["schemas"]["SimilarReleaseItemDto"][] | null;
            flavor?: string | null;
            model?: string | null;
        };
        SimilarTrackItemDto: {
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            /** Format: float */
            score?: number;
            /** Format: float */
            relevance?: number;
        };
        SimilarTracksResponseDto: {
            items?: components["schemas"]["SimilarTrackItemDto"][] | null;
            source?: string | null;
            model?: string | null;
        };
        TagDto: {
            /** @example tag_00000000000000000000000000 */
            id?: string;
            name?: string | null;
        };
        TrackCreditDto: {
            role?: components["schemas"]["CreditRole"];
            name?: string | null;
        };
        TrackCreditGroupDto: {
            role: components["schemas"]["CreditRole"];
            names: string[] | null;
        };
        TrackCreditsWriteDto: {
            credits: components["schemas"]["TrackCreditGroupDto"][] | null;
        };
        TrackListItemDto: {
            /** @example trk_00000000000000000000000000 */
            id?: string;
            /** Format: int32 */
            track_number?: number;
            name?: components["schemas"]["LocalizedField"];
            /** Format: date-span */
            duration?: string | null;
            has_media?: boolean;
            has_lyrics?: boolean;
        };
        TrackMapCircleDto: {
            /** @example cir_00000000000000000000000000 */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            count?: number;
        };
        TrackMapClusterDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
        };
        TrackMapResponseDto: {
            /** Format: int32 */
            count?: number;
            model?: string | null;
            works?: components["schemas"]["TrackMapWorkDto"][] | null;
            circles?: components["schemas"]["TrackMapCircleDto"][] | null;
            clusters?: components["schemas"]["TrackMapClusterDto"][] | null;
            ids?: string[] | null;
            x?: number[] | null;
            y?: number[] | null;
            cluster?: number[] | null;
            year?: number[] | null;
            work?: number[] | null;
            circle?: number[] | null;
        };
        TrackMapWorkDto: {
            /** @example work_00000000000000000000000000 */
            id?: string;
            short_name?: components["schemas"]["LocalizedField"];
        };
        TrackOriginalsWriteDto: {
            song_external_keys: string[] | null;
        };
        TrackReadDto: {
            /** @example trk_00000000000000000000000000 */
            id?: string;
            /** Format: int32 */
            track_number?: number;
            name?: components["schemas"]["LocalizedField"];
            /** Format: date-span */
            duration?: string | null;
            original_non_touhou?: boolean | null;
            /** @example dsc_00000000000000000000000000 */
            disc_id?: string;
            /** Format: int32 */
            disc_number?: number;
            release?: components["schemas"]["ReleaseSlimDto"];
            circles?: components["schemas"]["CircleSlimDto"][] | null;
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
            has_media?: boolean;
            hls_bitrates?: number[] | null;
            has_dash?: boolean;
            credits?: components["schemas"]["TrackCreditDto"][] | null;
            tags?: components["schemas"]["TagDto"][] | null;
            original_songs?: components["schemas"]["OriginalSongSlimDto"][] | null;
            has_lyrics?: boolean;
        };
        TrackWithContext: {
            track?: components["schemas"]["TrackListItemDto"];
            release?: components["schemas"]["ReleaseSlimDto"];
            /** @example art_00000000000000000000000000 */
            artwork_id?: string | null;
            circles?: components["schemas"]["CircleSlimDto"][] | null;
        };
        TrackWithContextCursorPage: {
            items?: components["schemas"]["TrackWithContext"][] | null;
            next?: string | null;
        };
        UserProfileReadDto: {
            /** @example usr_00000000000000000000000000 */
            id?: string;
            display_name?: string | null;
            /** Format: date-time */
            date_joined?: string;
        };
        UserProfileWriteDto: {
            display_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
